// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/demeyerthom/tesseract-api/internal/models"
)

// ConvertOKCode is the HTTP code returned for type ConvertOK
const ConvertOKCode int = 200

/*ConvertOK pet response

swagger:response convertOK
*/
type ConvertOK struct {

	/*
	  In: Body
	*/
	Payload *models.ParsedImage `json:"body,omitempty"`
}

// NewConvertOK creates ConvertOK with default headers values
func NewConvertOK() *ConvertOK {

	return &ConvertOK{}
}

// WithPayload adds the payload to the convert o k response
func (o *ConvertOK) WithPayload(payload *models.ParsedImage) *ConvertOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the convert o k response
func (o *ConvertOK) SetPayload(payload *models.ParsedImage) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ConvertOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
