// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ConvertHandlerFunc turns a function with the right signature into a convert handler
type ConvertHandlerFunc func(ConvertParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ConvertHandlerFunc) Handle(params ConvertParams) middleware.Responder {
	return fn(params)
}

// ConvertHandler interface for that can handle valid convert params
type ConvertHandler interface {
	Handle(ConvertParams) middleware.Responder
}

// NewConvert creates a new http.Handler for the convert operation
func NewConvert(ctx *middleware.Context, handler ConvertHandler) *Convert {
	return &Convert{Context: ctx, Handler: handler}
}

/*Convert swagger:route POST /convert convert

Converts the given image to text

*/
type Convert struct {
	Context *middleware.Context
	Handler ConvertHandler
}

func (o *Convert) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewConvertParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
