// Code generated by go-swagger; DO NOT EDIT.

/*
Package internal Tesseract API
A simple API to pass files to tesseract over HTTP


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0

    Consumes:
    - application/json
    - multipart/form-data

    Produces:
    - application/json

swagger:meta
*/
package internal
